backend:
  name: github
  repo: kpserhiiliashko-blip/kp-web
  branch: main
  auth_scope: repo
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "news"
    label: "Новини"
    folder: "src/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Анонс", name: "excerpt", widget: "text", required: false }
      - { label: "Текст", name: "body", widget: "markdown" }
